import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export const getHomeRoute = () => {
  return '/login';
  // if (role === UserRoleType.ROLE_CLIENTE) return '/dashboard';
  // else return '/dashboard';
};

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    if (!router.isReady) {
      return;
    }
    const homeRoute = getHomeRoute();

    router.replace(homeRoute);

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Find Architect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
